### ISSUE TITLE
New UI for Categories list

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#16]
The Categories screen would probably benefit from having tabs (in order to separate incomes from expenses) and a card interface, as shown here:

![financius category 1](https://f.cloud.github.com/assets/694794/1510150/d9c6d3ba-4a74-11e3-95dc-cbfb88ee99c3.png)

As for the Category details screen, here's an interface proposal for it:

![financius category 2](https://f.cloud.github.com/assets/694794/1510151/dcfb4a16-4a74-11e3-9638-636c3370a8ef.png)

The different tabs separate all its subcategories, and the screen has a details card plus history cards similar to those described on issue #13.

**Comment by mvarnagiris** [comment]
The list of categories makes sense and looks good. But detail screen is again too complicated

**Comment by frandavid100** [comment]
Can you give me some feedback on what parts of it you think clutter the screen? Maybe I can simplify it more.

**Comment by shahrilamrias** [comment]
About the list of categories...

I think it would be great if we're able to minimise the whole category (Food: Groceries, Lunch, Eating Out...) when I tap the main category so that only the main category (Food, Leisure, Billing...) is viewable. 

I believe this would come in handy if one is trying to find the specific category quickly without using the category search. Sometimes I just don't feel like typing or the category just didn't come to mind and I had to scroll all the way down only to find it at the bottom. hehe

**Comment by mvarnagiris** [comment]
Well this is a tricky one. Some prefer always open, some prefer closed. I'll think how this could be made a little better

**Comment by shahrilamrias** [comment]
If it's a no, then you can just implement a scrollbar that we can actually touch to scroll around up/down with - you know,  like the one in Titanium Backup for example.

**Comment by mvarnagiris** [comment]
UI is changing for next release to material
