### ISSUE TITLE
v 0.11.3 Issue with reports

### ISSUE THREAD

**Issue by mano2win** [mvarnagiris/financius#188]
Reports does not have sub categories and does not have graph

**Comment by mano2win** [comment]
Cannot see how much amount is spend on groceries or a particular expense .. pls fix it.. and can also have a detailed report in each account so that it's easy to cross check expenses with bank statement..

**Comment by mano2win** [comment]
previous version was good... sub categories is a must...

**Comment by mvarnagiris** [comment]
Subcategories were removed. Use Tags instead. Reports for tags will be coming

**Comment by ghost** [comment]
Aw, I loved the old sub categories system. Currently, it takes quite a bit longer to add tags. I am presented with an enormous list of tags that I have to scroll through. I liked the old system because it was a lot quicker. Perhaps a way to categorize tags or something would make it better. The old categories system was the main thing I liked about your application. Please consider doing something to make it easier to use. Everything else is looking better and better though. Keep up the great work!

**Comment by ghost** [comment]
Here is a simple idea to make it quicker and easier to select tags. Currently, we have to scroll through a single large list to find the ones we want. My idea: when selecting tags, we could have certain tags under specific categories. So, you select 'Food' and it shows all the 'Food' tags. You could still select tags from multiple categories. It is just categorized to allow you to find them faster.

Also, a search function could be added to really speed things up a bit! Thanks again for all your work. Best finance manager by far
![financius tag selection](https://cloud.githubusercontent.com/assets/1057319/4962598/b9db9e32-66e3-11e4-81d7-dbcac582861b.jpg)

**Comment by mvarnagiris** [comment]
It will be easier to select tags and everything. I promise :)
