### ISSUE TITLE
JSON backup/restore from file

### ISSUE THREAD

**Issue by mvarnagiris** [mvarnagiris/financius#3]

**Comment by ansariNo1** [comment]
So far, I see an option to export, but no option to import. Currently, I'm using Expense Manager. I'm able to export my data from there, which is clean and clear, but no way to import it into Financius. If this ever gets implemented, I will be able to make the move to Financius.

**Comment by tdkl** [comment]
@ansariNo1 : You would  need to implement a specific import for every Expense manager app out there, since everyone uses their own export style. Initially it could be done maybe for top 3 apps, but even then there's no 99,9% guarantee that all data would be imported without issues. You also have to consider that many apps have a different way of the data structure (some use categories, some tags, some combo of both), not to mention how to handle non trivial category naming and translation to Financius categories.

**Comment by mvarnagiris** [comment]
This is now possible if file is uploaded to GoogleDrive

**Comment by mvarnagiris** [comment]
Backup and restore from file on phone is now done. Importing from other apps would still require changing format to Financius format. But it's better not to do that, because this way it's very easy bo corrupt the data.
