### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by i1senthilcse** [mvarnagiris/financius#54]
Can we have a new option called Tags?

Currently we are classifying our income and expenses using Categories. During each transaction, user can also 'Tag' their expenses (optional field). 

The main use of Tags will be: 
- These tags may be used to denote:
  (i) Expense type (denoting user's expense -> whether user spent money on some useful items or spend on luxurious/waste items) or 
  (ii) Mode of expense (payment) etc.
- We can have a view for tags (similar to transactions), so that after a particular time -> users can review their transactions by tag.
- We can also provide a feature to customise tags (so that user can add/edit their tags).

**Comment by marcovrv** [comment]
These feature may be implemented with "hashtag style", with # for tags, @ for contacts, etc. directly in the notes field, so there wouldn't be need for a separate field. This way is truly optional.

**Comment by MartiCode** [comment]
I like the hashtag idea but there would need to be some autocomplete as this might be tedious to type every time. Tags are really useful for cross-category grouping too (ie: "car insurance" would go with the "car" category, but it is also useful if you can tag with "insurance" so that you can see how much you spend on all your insurances contracts).

**Comment by mvarnagiris** [comment]
Tags is a good suggestions. I was thinking about this as well.

**Comment by i1senthilcse** [comment]
Thank You.

**Comment by mvarnagiris** [comment]
Done
