### ISSUE TITLE
List of minor UI and UX changes

### ISSUE THREAD

**Issue by leoetlino** [mvarnagiris/financius#74]
This summarizes issue #72 in a nice check list, so that it is easier to follow the progress.
## _Add/Edit a transaction_ views
- [ ] Remove the _Discard_ button and instead use something more consistent with other apps and the system such as:

```
[< Add/Edit a transaction]                                (to the right) [Done ✓]
```
- [ ] Reduce the number of user interactions required to add a new transaction. (Make the amount keyboard and categories inline, for example.)
- [ ] **bug**: The form validation errors do not show up if animations are disabled in the system settings.
## General
- [ ] Add incomes into transactions summary as well as expenses.
- [ ] Make the color squares smaller (about 6-10%).
- [ ] Add a border to the color squares.
- [ ] Hide optional fields and/or details per default, and show them when the user requests it. (That could be implemented with a checkbox in the action bar's overflow menu.)
- [ ] Remove the month in the color squares for transactions.
## _Categories_ views
- [ ] Use a layout similar to DashClock's (for more details, see #72, second image). 
- [ ] Use _Categories_ instead of _Categories report_, on the summary page (not the full view).
- [ ] Remove the percent sign (_%_) on the categories report full view.

**Comment by leoetlino** [comment]
Personally, I'm against changing the color squares in any way - I think they are already perfect with the current implementation. And there's no need in my opinion to remove the percent sign - it's not obvious for everyone.

As for using _Categories_ instead of _Categories report_, again, I'm not too sure if I would agree with that.

Any feedback?

**Comment by assoc** [comment]
I want clarify something (add to text):
1. Remove ARROW before Discard button (cause it is independent element with same function). Concept is discard/done select. (see 1st image, right part).
2. Form validation with tooltips or color (now it not work with disabled android animations).
3. Hide optional things (time and using in reports) by special option like "minimal mode".
4. Reduse interactions; !important: start dialog with user via input sum (-1), replace category selector by "frequent categories"+selector button.
5. Just add line of incomes to diagram.
6. Change "color squares": make it a LITTLE BIT smaller (up to 6-10%), add border (1px), remove months in confirmed transactions, remove % (because it is pie chart, pie=100%, obvious).

About squares - just opinion.

**Comment by leoetlino** [comment]
1. I agree that the concept would be Discard/Done, but, that's not what other apps and the Android system use and we wouldn't know what we're doing at the first time.
2. I'll add that.
3. It's already there, but, I'll move it to _General_.
4. I'll add that.
5. Already done.
6. I'll precise a little more.

**Comment by leoetlino** [comment]
Removing the month and the % sign is probably going to be **confusing**. The fact that it's obvious to _you_ does not mean that it's obvious for _everyone_. _In my opinion_, it'd be better to leave it as is, but, let's see what others want?

**Comment by assoc** [comment]
Possible compromise: http://i.imgur.com/jBsP8mM.png

**Comment by mvarnagiris** [comment]
As I said in #72 Please make all UI suggestions each in separate issue as this is impossible to process and discuss
